### ISSUE TITLE
warp mode [feature request]

### ISSUE THREAD

**Issue by jeffbrl** [amirdaaee/cloudflare-warp-docker#5]
Thank you for sharing this container build. I find it enormously helpful when I need a local web proxy that uses warp for connectivity.

For some use cases that cannot accommodate web proxy, I would like to use cloudflare-warp-docker similar to how [gluetun](https://github.com/qdm12/gluetun) is used.

Here is an example docker compose file.

```
services:
  warp:
    image: amirdaaee/cloudflare-warp:latest
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    network_mode: "service:warp"
```

I tried to modify your run.sh to change warp's mode from "proxy" to "warp". I believe doing so would create the cloudflare warp tunnel interface. I ran into many problems with the change in warp syntax for the latest warp client and problems related to dbus in a container. I was unsuccessful.
